// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro',
    'downloads',
    {
      type: 'category',
      label: 'Agent 實戰課程',
      link: {type: 'doc', id: 'ai-agents/overview'},
      collapsed: true,
      items: [
        {type: 'doc', id: 'ai-agents/foundation/what-is-agent', label: '01.01 什麼是 Agent'},
        {type: 'doc', id: 'ai-agents/foundation/use-cases', label: '01.02 使用情境'},
        {type: 'doc', id: 'ai-agents/environment/python-setup', label: '02.01 Python 環境'},
        {type: 'doc', id: 'ai-agents/environment/llm-providers', label: '02.02 LLM 供應商'},
        {type: 'doc', id: 'ai-agents/environment/course-api-gateway', label: '02.03 課程 API Gateway'},
        {type: 'doc', id: 'ai-agents/langchain-core/overview', label: '03.01 LangChain 概覽'},
        {type: 'doc', id: 'ai-agents/langchain-core/models-messages', label: '03.02 Model 與 Messages'},
        {type: 'doc', id: 'ai-agents/langchain-core/prompts', label: '03.03 Prompt Template'},
        {type: 'doc', id: 'ai-agents/langchain-core/structured-output', label: '03.04 Structured Output'},
        {type: 'doc', id: 'ai-agents/langchain-core/streaming', label: '03.05 Streaming'},
        {type: 'doc', id: 'ai-agents/tools/tool-concept', label: '04.01 Tool Use 概念'},
        {type: 'doc', id: 'ai-agents/tools/builtin-tools', label: '04.02 內建 Tool'},
        {type: 'doc', id: 'ai-agents/tools/custom-tools', label: '04.03 自訂 Tool'},
        {type: 'doc', id: 'ai-agents/tools/agent-tool-loop', label: '04.04 Agent Loop'},
        {type: 'doc', id: 'ai-agents/langgraph-intro/why-graph', label: '05.01 為什麼需要 Graph'},
        {type: 'doc', id: 'ai-agents/langgraph-intro/simple-graph', label: '05.02 Simple Graph'},
        {type: 'doc', id: 'ai-agents/langgraph-intro/state-reducer', label: '05.03 State & Reducer'},
        {type: 'doc', id: 'ai-agents/langgraph-intro/react-agent', label: '05.04 ReAct Agent'},
        {type: 'doc', id: 'ai-agents/memory/short-term', label: '06.01 短期記憶'},
        {type: 'doc', id: 'ai-agents/memory/summarization', label: '06.02 摘要 & Trim'},
        {type: 'doc', id: 'ai-agents/memory/external-store', label: '06.03 外部儲存'},
        {type: 'doc', id: 'ai-agents/memory/long-term-memory', label: '06.04 長期記憶'},
        {type: 'doc', id: 'ai-agents/hitl/breakpoints', label: '07.01 Breakpoints'},
        {type: 'doc', id: 'ai-agents/hitl/interrupts', label: '07.02 interrupt()'},
        {type: 'doc', id: 'ai-agents/hitl/edit-state', label: '07.03 編輯 State'},
        {type: 'doc', id: 'ai-agents/hitl/time-travel', label: '07.04 Time Travel'},
        {type: 'doc', id: 'ai-agents/multi-agent/patterns', label: '08.01 Multi-Agent 模式'},
        {type: 'doc', id: 'ai-agents/multi-agent/supervisor', label: '08.02 Supervisor'},
        {type: 'doc', id: 'ai-agents/multi-agent/parallelization', label: '08.03 平行化'},
        {type: 'doc', id: 'ai-agents/multi-agent/research-assistant', label: '08.04 研究助理實戰'},
        {type: 'doc', id: 'ai-agents/rag/rag-basics', label: '09.01 RAG 基礎'},
        {type: 'doc', id: 'ai-agents/rag/vector-stores', label: '09.02 Vector Store'},
        {type: 'doc', id: 'ai-agents/rag/retrievers', label: '09.03 Retriever'},
        {type: 'doc', id: 'ai-agents/rag/agentic-rag', label: '09.04 Agentic RAG'},
        {type: 'doc', id: 'ai-agents/production/observability', label: '10.01 Observability'},
        {type: 'doc', id: 'ai-agents/production/deployment', label: '10.02 部署'},
        {type: 'doc', id: 'ai-agents/production/guardrails', label: '10.03 Guardrails'},
        {type: 'doc', id: 'ai-agents/production/mcp', label: '10.04 MCP'},
      ],
    },
    {
      type: 'category',
      label: 'EdgeAI 實戰課程',
      link: {type: 'doc', id: 'ai-sensor-mpu6050/overview'},
      collapsed: true,
      items: [
        {type: 'doc', id: 'ai-sensor-mpu6050/hardware-setup', label: '01. 硬體與接線'},
        {type: 'doc', id: 'ai-sensor-mpu6050/environment', label: '02. 開發環境'},
        {type: 'doc', id: 'ai-sensor-mpu6050/peripheral-tests', label: '03. 周邊自測'},
        {type: 'doc', id: 'ai-sensor-mpu6050/data-collection', label: '04. 資料擷取'},
        {type: 'doc', id: 'ai-sensor-mpu6050/edge-impulse', label: '05. Edge Impulse 訓練'},
        {type: 'doc', id: 'ai-sensor-mpu6050/inference', label: '06. 裝置端推論'},
        {type: 'doc', id: 'ai-sensor-mpu6050/aiot-mqtt', label: '07. Wi-Fi 與 MQTT'},
        {type: 'doc', id: 'ai-sensor-mpu6050/troubleshooting', label: '08. 疑難排解'},
      ],
    },
    {
      type: 'category',
      label: 'Vision 實戰課程',
      link: {type: 'doc', id: 'computer-vision-course/overview'},
      collapsed: true,
      items: [
        {type: 'doc', id: 'computer-vision-course/environment-setup', label: '00. 環境設定'},
        {type: 'doc', id: 'computer-vision-course/day1-opencv-basics', label: '01. OpenCV 入門'},
        {type: 'doc', id: 'computer-vision-course/day2-mediapipe-pose', label: '02. Mediapipe 姿勢'},
        {type: 'doc', id: 'computer-vision-course/day3-yolo-finetune', label: '03. YOLO11 微調'},
        {type: 'doc', id: 'computer-vision-course/day4-high-res-image', label: '04. 高解析影像'},
        {type: 'doc', id: 'computer-vision-course/day5-customtkinter-gui', label: '05. CustomTkinter GUI'},
        {type: 'doc', id: 'computer-vision-course/day6-smart-inspection', label: '06. 智慧檢測整合'},
      ],
    },
    {
      type: 'category',
      label: 'OpenWebUI 擴充開發指南',
      link: {type: 'doc', id: 'openwebui-extensibility/overview'},
      collapsed: true,
      items: [
        {type: 'doc', id: 'openwebui-extensibility/tools', label: '01. Tools'},
        {type: 'doc', id: 'openwebui-extensibility/pipe-functions', label: '02. Pipe Functions'},
        {type: 'doc', id: 'openwebui-extensibility/filter-functions', label: '03. Filter Functions'},
        {type: 'doc', id: 'openwebui-extensibility/action-functions', label: '04. Action Functions'},
        {type: 'doc', id: 'openwebui-extensibility/mcp', label: '05. MCP 整合'},
        {type: 'doc', id: 'openwebui-extensibility/pipelines', label: '06. Pipelines'},
        {type: 'doc', id: 'openwebui-extensibility/common-pitfalls', label: '07. 常見反官方寫法' },
      ],
    },
  ],
};

export default sidebars;
